### ISSUE TITLE
training on  LEVIR-CD 

### ISSUE THREAD

**Issue by derow0208** [wgcban/ChangeFormer#100]
thanks for your excellent work! i have down load your customized LEVIR-CD256x256, but i don not know how to change the path in the run_ChangeFormer_LEVIR.sh, as i do not find any param about the training dataset. Additionally, you initialize your net with a model pre-trained on the RGB segmentation (ADE 160k dataset) ,but you just give me link to the pretrained 'CD_ChangeFormerV6_LEVIR_b16_lr0.0001_adamw_train_test_200_linear_ce_multi_train_True_multi_infer_False_shuffle_AB_False_embed_dim_256', dose that mean i need to initialize the net with pretrained changeformer model?

**Comment by derow0208** [comment]
what's more, as i only have three gpus，each with 12GB memory. i change the params 'gpus' from '0' to '0,1,2', but it dosen't work. what should i do

**Comment by derowtosky** [comment]
> what's more, as i only have three gpus，each with 12GB memory. i change the params 'gpus' from '0' to '0,1,2', but it dosen't work. what should i do
specific error information was here:
(changeformer) pengyw@luoxy-MS-7A91:~/ChangeFormer$ bash scripts/run_ChangeFormer_LEVIR.sh
True
[0, 1, 2]
Traceback (most recent call last):
  File "main_cd.py", line 83, in <module>
    train(args)
  File "main_cd.py", line 14, in train
    model = CDTrainer(args=args, dataloaders=dataloaders)
  File "/home/pengyw/ChangeFormer/models/trainer.py", line 30, in __init__
    self.net_G = define_G(args=args, gpu_ids=args.gpu_ids)
  File "/home/pengyw/ChangeFormer/models/networks.py", line 184, in define_G
    return init_net(net, init_type, init_gain, gpu_ids)
  File "/home/pengyw/ChangeFormer/models/networks.py", line 122, in init_net
    net = torch.nn.DataParallel(net, gpu_ids)  # multi-GPUs
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 142, in __init__
    _check_balance(self.device_ids)
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 23, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/_utils.py", line 464, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/_utils.py", line 464, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/_utils.py", line 447, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/_utils.py", line 464, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/cuda/__init__.py", line 359, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

**Comment by derow0208** [comment]
> what's more, as i only have three gpus，each with 12GB memory. i change the params 'gpus' from '0' to '0,1,2', but it dosen't work. what should i do

specific error information was here:
(changeformer) pengyw@luoxy-MS-7A91:~/ChangeFormer$ bash scripts/run_ChangeFormer_LEVIR.sh
True
[0, 1, 2]
Traceback (most recent call last):
  File "main_cd.py", line 83, in <module>
    train(args)
  File "main_cd.py", line 14, in train
    model = CDTrainer(args=args, dataloaders=dataloaders)
  File "/home/pengyw/ChangeFormer/models/trainer.py", line 30, in __init__
    self.net_G = define_G(args=args, gpu_ids=args.gpu_ids)
  File "/home/pengyw/ChangeFormer/models/networks.py", line 184, in define_G
    return init_net(net, init_type, init_gain, gpu_ids)
  File "/home/pengyw/ChangeFormer/models/networks.py", line 122, in init_net
    net = torch.nn.DataParallel(net, gpu_ids)  # multi-GPUs
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 142, in __init__
    _check_balance(self.device_ids)
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 23, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/_utils.py", line 464, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/_utils.py", line 464, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/_utils.py", line 447, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/_utils.py", line 464, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/pengyw/anaconda3/envs/changeformer/lib/python3.8/site-packages/torch/cuda/__init__.py", line 359, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
waiting for you reply to help a newcomer of CD

**Comment by wgcban** [comment]
@derowtosky Pre-trained model is to make the model converge faster. Even without pre-trained models, you will be able to get the results presented in the paper.
When training with more than one GPUs, additional modifications required. Please check the related issues -- people have already pointed out necessary modifications to run it on multiple-gpus.

Thanks

**Comment by wgcban** [comment]
For example see issue: #90

**Comment by wgcban** [comment]
You can wrap the model with Data Parallel in order to run it with multiple gpus.

**Comment by derow0208** [comment]
@wgcban thank you for your reply!
