### ISSUE TITLE
Facing issue in downloading the pre trained model on LEVIR dataset

### ISSUE THREAD

**Issue by ayshaashra** [wgcban/ChangeFormer#110]
I am interested to run the code on LEVIR-dataset for comparison, I have setup Linux on my system using CMD. i have clone the ChangeFormer into it.  Next steps are as follow: 

1. wsl
2. cd ~/ChangeFormer
3. $ python3 demo_LEVIR.py

 **_(when i run this command i got error
aysha@DESKTOP-9U7U2SJ:~/ChangeFormer$ python3 demo_LEVIR.py
initialize network with normal
cuda:0
Traceback (most recent call last):
  File "/home/aysha/ChangeFormer/demo_LEVIR.py", line 66, in <module>
    model.load_checkpoint(args.checkpoint_name)
  File "/home/aysha/ChangeFormer/models/basic_model.py", line 42, in load_checkpoint
    raise FileNotFoundError('no such checkpoint %s' % checkpoint_name)
FileNotFoundError: no such checkpoint best_ckpt.pt )_**

after that i am going to a link to dowload it from google colab, where i have uploaded the model file :

4. wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1QKn0AL5_LGBG5o2dr0s0oAcwxYhrvqx6" -O best_ckpt.pt

i am facing error each time **_failed: Network is unreachable._** 

after that i manually download and insert the best_ckpt.pt file in folder.

**Comment by ayshaashra** [comment]
I am not able to download pretrained_changeformer.pt as given link contains file : 
1. train_acc.npy
2. best_ckpt.pt
3. last_ckpt.pt
4. log.txt
5. val_acc.npy

how to get pretrained_changeformer.pt when i run wget https://www.dropbox.com/s/undtrlxiz7bkag5/pretrained_changeformer.pt  
Failed to connect to www.dropbox.com port 443 after 21265 ms: Couldn't connect to server 

is best_ckpt.pt or pretrained_changeformer.pt refer to same file ? @wgcban

**Comment by derow0208** [comment]
best_ckpt.pt is the checkpoint you need, replace the checkpoints path in config with your/path/to/checkpoints
