### ISSUE TITLE
Input and output must have the same number of spatial dimensions.

### ISSUE THREAD

**Issue by zdw9915** [wgcban/ChangeFormer#47]

**Comment by zdw9915** [comment]
Traceback (most recent call last):
  File "D:\program files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\program files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Users/Zhou/PycharmProjects/ChangeFormer/main_cd.py", line 83, in <module>
    train(args)
  File "D:/Users/Zhou/PycharmProjects/ChangeFormer/main_cd.py", line 15, in train
    model.train_models()
  File "D:\Users\Zhou\PycharmProjects\ChangeFormer\models\trainer.py", line 330, in train_models
    self._backward_G()
  File "D:\Users\Zhou\PycharmProjects\ChangeFormer\models\trainer.py", line 306, in _backward_G
    self.G_loss = self._pxl_loss(self.G_pred[-1], gt)
  File "D:\Users\Zhou\PycharmProjects\ChangeFormer\models\losses.py", line 19, in cross_entropy
    input = F.interpolate(input, size=target.shape[1:], mode='bilinear',align_corners=True)
  File "E:\Users\Zhou\anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 3862, in interpolate
    raise ValueError(
ValueError: Input and output must have the same number of spatial dimensions, but got input with with spatial dimensions of [256, 256] and output size of torch.Size([1, 256, 256, 3]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.

**Comment by zdw9915** [comment]
How to solve this problem, please? Thank you

**Comment by wgcban** [comment]
@zdw9915 I think this is a problem with your gt data. I think it has 3 channels as the error msg says. just take only one channel. 

Check Line 114 in CD_dataset.py: https://github.com/wgcban/ChangeFormer/blob/9025e26417cf8f10f29a48f34a05758498216465/datasets/CD_dataset.py#L114
 
To solve this problem change `label = np.array(Image.open(L_path), dtype=np.uint8)` tp `label = np.array(Image.open(L_path), dtype=np.uint8)[:,:,0]`

**Comment by zdw9915** [comment]
The error has been solved, thank you very much, and I wish you a happy life！




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "wgcban/ChangeFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 晚上11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wgcban/ChangeFormer] Input and output must have the same number of spatial dimensions. (Issue #47)





 
@zdw9915 I think this is a problem with your gt data. I think it has 3 channels as the error msg says. just take only one channel.
 
Check Line 114 in CD_dataset.py: https://github.com/wgcban/ChangeFormer/blob/9025e26417cf8f10f29a48f34a05758498216465/datasets/CD_dataset.py#L114
 
To solve this problem change label = np.array(Image.open(L_path), dtype=np.uint8) tp label = np.array(Image.open(L_path), dtype=np.uint8)[:,:,0]
